config/routes.rb
Rails.application.routes.draw do
  
  resources :tag
  
  root "cities#index"



  resources :users, only: [:create, :update]
  get "/signup", to: "users#new", as: :signup
  get "/profile", to: "users#show", as: :profile
  get "/edit-profile", to: "users#edit", as: :edit_profile

  resources :sessions, only: [:create]
  get "/login", to: "sessions#new", as: :login
  get "/logout", to: "sessions#destroy", as: :logout

  resources :cities, only: [:index, :show] do
    resources :posts, shallow: true
  end

  resources :posts, shallow: true do
    resources :comments, shallow: true
  end

  get "/:id", to: "cities#show"

end

#           Prefix Verb   URI Pattern                            Controller#Action
#             root GET    /                                      cities#index
#            users POST   /users(.:format)                       users#create
#             user PATCH  /users/:id(.:format)                   users#update
#                  PUT    /users/:id(.:format)                   users#update
#           signup GET    /signup(.:format)                      users#new
#          profile GET    /profile(.:format)                     users#show
#     edit_profile GET    /edit-profile(.:format)                users#edit
#         sessions POST   /sessions(.:format)                    sessions#create
#            login GET    /login(.:format)                       sessions#new
#           logout GET    /logout(.:format)                      sessions#destroy
#       city_posts GET    /cities/:city_id/posts(.:format)       posts#index
#                  POST   /cities/:city_id/posts(.:format)       posts#create
#    new_city_post GET    /cities/:city_id/posts/new(.:format)   posts#new
#        edit_post GET    /posts/:id/edit(.:format)              posts#edit
#             post GET    /posts/:id(.:format)                   posts#show
#                  PATCH  /posts/:id(.:format)                   posts#update
#                  PUT    /posts/:id(.:format)                   posts#update
#                  DELETE /posts/:id(.:format)                   posts#destroy
#           cities GET    /cities(.:format)                      cities#index
#             city GET    /cities/:id(.:format)                  cities#show
#    post_comments GET    /posts/:post_id/comments(.:format)     comments#index
#                  POST   /posts/:post_id/comments(.:format)     comments#create
# new_post_comment GET    /posts/:post_id/comments/new(.:format) comments#new
#     edit_comment GET    /comments/:id/edit(.:format)           comments#edit
#          comment GET    /comments/:id(.:format)                comments#show
#                  PATCH  /comments/:id(.:format)                comments#update
#                  PUT    /comments/:id(.:format)                comments#update
#                  DELETE /comments/:id(.:format)                comments#destroy
#            posts GET    /posts(.:format)                       posts#index
#                  POST   /posts(.:format)                       posts#create
#         new_post GET    /posts/new(.:format)                   posts#new
#                  GET    /posts/:id/edit(.:format)              posts#edit
#                  GET    /posts/:id(.:format)                   posts#show
#                  PATCH  /posts/:id(.:format)                   posts#update
#                  PUT    /posts/:id(.:format)                   posts#update
#                  DELETE /posts/:id(.:format)                   posts#destroy
#                  GET    /:id(.:format)                         cities#show

app/models/user.rb
class User < ActiveRecord::Base

	has_secure_password
	has_many :posts, dependent: :destroy

	validates :password, length: { minimum: 6 }, on: :create

  	validates :email,
    presence: true,
    uniqueness: true,
    format: {
      with: /@/,
      message: "not a valid format"
    }

  
# attr_accessible :avatar
  has_attached_file :avatar,
                    :styles => { :medium => "150x150>", :thumb => "44x44#" },
                    :storage => :s3,
                    :s3_credentials => Proc.new { |a| a.instance.s3_credentials },
                    :path => "avatars/:id/:style/avatar.:extension",
                    :default_url => "https://s3.amazonaws.com/defaults-vagabond/default_avatar.png"


  validates_attachment :avatar,
                        :content_type => { :content_type => ["image/jpeg", "image/jpg", "image/gif", "image/png"] },
                        :size => { :in => 0..1000.kilobytes }



def s3_credentials
 { :bucket => ENV['S3_BUCKET'], :access_key_id => ENV['S3_PUBLIC_KEY'], :secret_access_key => ENV['S3_SECRET'] }
end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_filter :authorize, only: [:show]
  def new
    # redirect user if already logged in
    if current_user
      redirect_to profile_path
    else
      render :new
    end
  end

  def create
    # redirect user if already logged in
    if current_user
      redirect_to profile_path
    else
      user = User.new(user_params)
      if user.save
        session[:user_id] = user.id
        flash[:notice] = "Successfully signed up."
        redirect_to profile_path
      else
        flash[:error] = user.errors.full_messages.join(', ')
        redirect_to signup_path
      end
    end
  end

  def update
    user = User.find(params[:id])
    if current_user
      flash[:notice] = "Successfully updated profile!"
      user.update_attributes(user_params)
      redirect_to profile_path
    else
      flash[:error] = user.errors.full_messages.join(', ')
      redirect_to edit_profile_path
    end
  end

  def edit
    @user = User.find(current_user)
  end

  def destroy
    @user = User.find(params[:id])
    if current_user
      flash[:error] = "Successfully deleted profile!"
      user.destroy
      redirect_to cities_path
    end
  end

  def index
  end

  def show
    render :show
  end

  private
    def user_params
      params.require(:user).permit(:username, :email, :password, :password_confirmation, :location, :avatar)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class="text-center">
	<h1>Edit Profile</h1>
</div>
<div class="row">
	<div class="col-md-4 col-md-offset-4">
		<hr>
		<%= form_for @user, :html => { :multipart => true } do |f| %>
		<div class="form-group">
			<label for="exampleInputPassword1">Username</label>
			<%= f.text_field :username, placeholder: "Username", autofocus: true, class: "form-control" %>
		</div>
		<div class="form-group">
			<label for="exampleInputPassword1">Email</label>
			<%= f.email_field :email, placeholder: "Email", class: "form-control" %>
		</div>
		<div class="form-group">
			<label for="exampleInputPassword1">Password</label>
			<%= f.password_field :password, placeholder: "Password", class: "form-control" %>
		</div>
		<div class="form-group">
			<label for="exampleInputPassword1">Location</label>
			<%= f.text_field :location, placeholder: "Where You At?", class: "form-control" %>
		</div>
		<div class="form-group">
			<label for="exampleInputPassword1">Avatar</label>
			<%= f.file_field :avatar %>
			<p class="help-block">Avatar is optional</p>
		</div>

		<%= f.submit "Submit", class: "btn btn-primary btn-block" %>
		<% end %>

		<br>
		<p>Already have an account? <%= link_to "Click here", login_path%> to log in.</p>
	</div>
</div>

app/views/users/new.html.erb
<div class="text-center">
	<h1>Sign Up</h1>
</div>
<div class="row">
	<div class="col-md-4 col-md-offset-4">
		<hr>
		<%= form_for :user, url: users_path, :html => { :multipart => true, :id => "new_user" } do |f| %>
		<div class="form-group">
			<label for="exampleInputPassword1">Username</label>
			<%= f.text_field :username, placeholder: "Username", autofocus: true, class: "form-control" %>
		</div>
		<div class="form-group">
			<label for="exampleInputPassword1">Email</label>
			<%= f.email_field :email, placeholder: "Email", class: "form-control" %>
		</div>
		<div class="form-group">
			<label for="exampleInputPassword1">Password</label>
			<%= f.password_field :password, placeholder: "Password", class: "form-control" %>
		</div>
		<div class="form-group">
			<label for="exampleInputPassword1">Location</label>
			<%= f.text_field :location, placeholder: "Where You At?", class: "form-control" %>
		</div>
		<div class="form-group">
			<label for="exampleInputPassword1">Avatar</label>
			<%= f.file_field :avatar %>
			<p class="help-block">Avatar is optional</p>
		</div>

		<%= f.submit "Sign Up", class: "btn btn-primary btn-block" %>
		<% end %>

		<br>
		<p>Already have an account? <%= link_to "Click here", login_path%> to log in.</p>
	</div>
</div>

app/views/users/show.html.erb
<div class="text-center">
</div>
<div class="container">
	<div class="row">
		<div class = "col-md-12">
			<% if current_user.posts.any? %>
				<div class="container">
					<div class="row">
							<div class="col-md-8 col-md-offset-2">
								<h2 id="profile-header">Profile</h2>
								<%= link_to "Edit Profile", edit_profile_path(@user), class: "btn btn-primary pull-right", id: "edit-profile-button" %>
								<br>	
							</div>
					</div>
				</div>
				<% current_user.posts.each do |post|  %>
				<div class="container">
					<div class="row">
						<div class="col-md-8 col-md-offset-2">
							<div class="panel panel-warning">
								<div class="panel-body">
									<p>Title: <%= post.title %> <br>Body: <%= post.body %> <br></p>
								</div>
								<% if post.user.id == session[:user_id] %>
								<div class="panel-footer">
									<%= link_to "Edit Post", edit_post_path(post), class: "btn btn-primary" %>
									<%= link_to "Delete Post",  post, method: :delete, class: "btn btn-danger"  %>
								</div>
								<% end %>
							</div>
						</div>
					</div>
				</div>
				<% end %>
			<% else %>
				<div class="text-center">
					<h4>You don't have any posts!</h4>
					<br>
				</div>
			<% end %>
		</div>
	</div>
</div>