config/routes.rb
Rails.application.routes.draw do
  
  resources :tag
  
  root "cities#index"



  resources :users, only: [:create, :update]
  get "/signup", to: "users#new", as: :signup
  get "/profile", to: "users#show", as: :profile
  get "/edit-profile", to: "users#edit", as: :edit_profile

  resources :sessions, only: [:create]
  get "/login", to: "sessions#new", as: :login
  get "/logout", to: "sessions#destroy", as: :logout

  resources :cities, only: [:index, :show] do
    resources :posts, shallow: true
  end

  resources :posts, shallow: true do
    resources :comments, shallow: true
  end

  get "/:id", to: "cities#show"

end

#           Prefix Verb   URI Pattern                            Controller#Action
#             root GET    /                                      cities#index
#            users POST   /users(.:format)                       users#create
#             user PATCH  /users/:id(.:format)                   users#update
#                  PUT    /users/:id(.:format)                   users#update
#           signup GET    /signup(.:format)                      users#new
#          profile GET    /profile(.:format)                     users#show
#     edit_profile GET    /edit-profile(.:format)                users#edit
#         sessions POST   /sessions(.:format)                    sessions#create
#            login GET    /login(.:format)                       sessions#new
#           logout GET    /logout(.:format)                      sessions#destroy
#       city_posts GET    /cities/:city_id/posts(.:format)       posts#index
#                  POST   /cities/:city_id/posts(.:format)       posts#create
#    new_city_post GET    /cities/:city_id/posts/new(.:format)   posts#new
#        edit_post GET    /posts/:id/edit(.:format)              posts#edit
#             post GET    /posts/:id(.:format)                   posts#show
#                  PATCH  /posts/:id(.:format)                   posts#update
#                  PUT    /posts/:id(.:format)                   posts#update
#                  DELETE /posts/:id(.:format)                   posts#destroy
#           cities GET    /cities(.:format)                      cities#index
#             city GET    /cities/:id(.:format)                  cities#show
#    post_comments GET    /posts/:post_id/comments(.:format)     comments#index
#                  POST   /posts/:post_id/comments(.:format)     comments#create
# new_post_comment GET    /posts/:post_id/comments/new(.:format) comments#new
#     edit_comment GET    /comments/:id/edit(.:format)           comments#edit
#          comment GET    /comments/:id(.:format)                comments#show
#                  PATCH  /comments/:id(.:format)                comments#update
#                  PUT    /comments/:id(.:format)                comments#update
#                  DELETE /comments/:id(.:format)                comments#destroy
#            posts GET    /posts(.:format)                       posts#index
#                  POST   /posts(.:format)                       posts#create
#         new_post GET    /posts/new(.:format)                   posts#new
#                  GET    /posts/:id/edit(.:format)              posts#edit
#                  GET    /posts/:id(.:format)                   posts#show
#                  PATCH  /posts/:id(.:format)                   posts#update
#                  PUT    /posts/:id(.:format)                   posts#update
#                  DELETE /posts/:id(.:format)                   posts#destroy
#                  GET    /:id(.:format)                         cities#show

app/models/post.rb
class Post < ActiveRecord::Base

	acts_as_taggable	

	belongs_to :user
	belongs_to :city

	validates :title, length: { minimum: 2, maximum: 200}
	validates :body, length: { minimum: 2}

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  
  before_filter :authorize, except: [:index, :show]

  @tags = Post.tag_counts_on(:tags)

  def index
    @posts = Post.all
    render :index
  end

  def new
    @post = Post.new
    @city = City.friendly.find(params[:city_id])
    render :new
  end

  def create
    @post = current_user.posts.create(post_params)
    @city = City.friendly.find(params[:city_id])
    @post.city_id = params[:city_id]
    if @post.save
      redirect_to city_path(@city)
    else
      flash[:error] = @post.errors.full_messages.join(', ')
      redirect_to new_city_post_path
    end
  end

  def show
    @post = Post.find(params[:id])
    render :show
  end

  def edit
    @post = Post.find(params[:id])
    if current_user.posts.include? @post
      render :edit
    else
      redirect_to profile_path
    end
  end

  def update
    post = Post.find(params[:id])
    if current_user.posts.include? post
        post.update_attributes(post_params)
        redirect_to post_path(post)
    else
      redirect_to profile_path
    end
  end

  def destroy
    post = Post.find(params[:id])
    if current_user.posts.include? post
      post.destroy
      redirect_to profile_path
    else
      redirect_to login_path
    end
  end

  private
    def post_params
      params.require(:post).permit(:title, :body, :tag_list)
    end
  
end

app/helpers/posts_helper.rb
module PostsHelper

  include ActsAsTaggableOn::TagsHelper

end

app/views/posts/_form.html.erb
<!-- <h1>Add A Post</h1> -->

<div class="container" id="container_form">
	<%= form_for :post, url: "/cities/#{@city.id}/posts", :html => {:class => "form-horizontal center", :id => "post_new"} do |f| %>
		<div class="form-group">
			<%= f.label :title, "Title:", class: "col-sm-2 control-label" %>
			<div class="col-sm-8">
		    <%= f.text_field :title, class: "form-control", placeholder: "Enter title" %>
		  </div>
		</div>
		<div class="form-group">
		  <%= f.label :body, "Body:", class: "col-sm-2 control-label" %>
		  <div class="col-sm-8">
		    <%= f.text_area :body, class: "form-control", placeholder: "Enter your advice here"%>
		  </div>
		</div>
		<div class="form-group">
  <%= f.label :tag_list, "Tags:",class: "col-sm-2 control-label" %>
  		<div class="col-sm-8">
  			<%= f.text_field :tag_list, class: "form-control", placeholder: "Tags (seperated by commas)" %>
			</div>
		</div>


			<%= f.submit "Submit", class: "btn btn-primary pull-right", id: "submit-button" %>  
 	<% end %>
</div>

app/views/posts/edit.html.erb
<h1 style="text-align:center">Edit Post</h1>

<div class="container" id="container_form">
	<%= form_for @post, :html => {:class => "form-horizontal center", :id => "post_new"} do |f| %>
		<div class="form-group">
			<%= f.label :title, "Title:", class: "col-sm-2 control-label" %>
			<div class="col-sm-8">
		    <%= f.text_field :title, class: "form-control", placeholder: "Enter title" %>
		  </div>
		</div>
		<div class="form-group">
		  <%= f.label :body, "Body:", class: "col-sm-2 control-label" %>
		  <div class="col-sm-8">
		    <%= f.text_area :body, class: "form-control", placeholder: "Enter your advice here"%>
		  </div>
		</div>
	<div class="form-group">
  		<%= f.label :tag_list, "Tags:",class: "col-sm-2 control-label" %>
  		<div class="col-sm-8">
  			<%= f.text_field :tag_list, class: "form-control", placeholder: "Tags (seperated by commas)" %>
			</div>
		</div>


			<%= f.submit "Submit", class: "btn btn-primary pull-right", id: "submit-button" %>  
 	<% end %>
</div>

app/views/posts/index.html.erb
<% if @posts.any? %>
	<div class="container">
		<div class="row">
			<div class="col-md-8 col-md-offset-2">
				<h2>Here's What People Are Saying</h2>
				<hr>
			</div>
		</div>
	</div>
	<% @posts.each do |post|  %>
	<div class="container">
		<div class="row">
			<div class="col-md-8 col-md-offset-2">
				<div class="panel panel-warning">
					<div class="panel-heading">
						<h3 class="panel-title">Created by: <%= post.user.username %> <%= image_tag post.user.avatar.url(:thumb) %></h3>
					</div>
					<div class="panel-body">
						<p>Title: <%= post.title %> <br>Body: <%= post.body %> <br></p>
					</div>
					<% if post.user.id == session[:user_id] %>
					<div class="panel-footer">
						<%= link_to "Edit Post", edit_post_path(post), class: "btn btn-primary" %>
						<%= link_to "Delete Post",  post, method: :delete, class: "btn btn-danger"  %>
					<% end %>
					</div>
				</div>
			</div>
		</div>
	</div>
	<% end %>
	<% else %>
	<div class="text-center">
		<h4>There are no posts!</h4>
		<br>
		<%= link_to "Add A Post", new_post_path, class: "btn btn-primary" %>
	</div>
<% end %>

app/views/posts/new.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-8 col-md-offset-2">
			<h1>Add A Post</h1>
			<br>
		</div>
	</div>
</div>
<%= render 'form' %>

app/views/posts/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <div class="panel panel-warning">
        <div class="panel-heading">
          <%= image_tag @post.user.avatar.url(:thumb) %>
          <h3 class="panel-title">Created by: <%= @post.user.username %></h3>
        </div>
        <div class="panel-body">
		      <p>Title: <%= @post.title %> <br>
		        Body: <%= @post.body %> <br>
            Tags: <% tag_cloud @post.tag_counts, %w{s m l} do |tag, css_class| %>
              <%= link_to tag.name, tag_path(tag.id), class: css_class %>
            <% end %>
        </p>
			 </div>
       <% if @post.user.id == session[:user_id] %>
       <div class="panel-footer">
        <%= link_to "Edit Post", edit_post_path(@post), class: "btn btn-primary" %>
        <%= link_to "Delete Post",  @post, method: :delete, class: "btn btn-danger"  %>
      <% end %>
			</div>
      </div>
    </div>
  </div>
</div>