config/routes.rb
Rails.application.routes.draw do
  
  resources :tag
  
  root "cities#index"



  resources :users, only: [:create, :update]
  get "/signup", to: "users#new", as: :signup
  get "/profile", to: "users#show", as: :profile
  get "/edit-profile", to: "users#edit", as: :edit_profile

  resources :sessions, only: [:create]
  get "/login", to: "sessions#new", as: :login
  get "/logout", to: "sessions#destroy", as: :logout

  resources :cities, only: [:index, :show] do
    resources :posts, shallow: true
  end

  resources :posts, shallow: true do
    resources :comments, shallow: true
  end

  get "/:id", to: "cities#show"

end

#           Prefix Verb   URI Pattern                            Controller#Action
#             root GET    /                                      cities#index
#            users POST   /users(.:format)                       users#create
#             user PATCH  /users/:id(.:format)                   users#update
#                  PUT    /users/:id(.:format)                   users#update
#           signup GET    /signup(.:format)                      users#new
#          profile GET    /profile(.:format)                     users#show
#     edit_profile GET    /edit-profile(.:format)                users#edit
#         sessions POST   /sessions(.:format)                    sessions#create
#            login GET    /login(.:format)                       sessions#new
#           logout GET    /logout(.:format)                      sessions#destroy
#       city_posts GET    /cities/:city_id/posts(.:format)       posts#index
#                  POST   /cities/:city_id/posts(.:format)       posts#create
#    new_city_post GET    /cities/:city_id/posts/new(.:format)   posts#new
#        edit_post GET    /posts/:id/edit(.:format)              posts#edit
#             post GET    /posts/:id(.:format)                   posts#show
#                  PATCH  /posts/:id(.:format)                   posts#update
#                  PUT    /posts/:id(.:format)                   posts#update
#                  DELETE /posts/:id(.:format)                   posts#destroy
#           cities GET    /cities(.:format)                      cities#index
#             city GET    /cities/:id(.:format)                  cities#show
#    post_comments GET    /posts/:post_id/comments(.:format)     comments#index
#                  POST   /posts/:post_id/comments(.:format)     comments#create
# new_post_comment GET    /posts/:post_id/comments/new(.:format) comments#new
#     edit_comment GET    /comments/:id/edit(.:format)           comments#edit
#          comment GET    /comments/:id(.:format)                comments#show
#                  PATCH  /comments/:id(.:format)                comments#update
#                  PUT    /comments/:id(.:format)                comments#update
#                  DELETE /comments/:id(.:format)                comments#destroy
#            posts GET    /posts(.:format)                       posts#index
#                  POST   /posts(.:format)                       posts#create
#         new_post GET    /posts/new(.:format)                   posts#new
#                  GET    /posts/:id/edit(.:format)              posts#edit
#                  GET    /posts/:id(.:format)                   posts#show
#                  PATCH  /posts/:id(.:format)                   posts#update
#                  PUT    /posts/:id(.:format)                   posts#update
#                  DELETE /posts/:id(.:format)                   posts#destroy
#                  GET    /:id(.:format)                         cities#show

app/models/city.rb
class City < ActiveRecord::Base
	has_many :posts, dependent: :destroy

	extend FriendlyId
	friendly_id :name, use: :slugged
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  def index
  	@cities = City.all
  	
  	respond_to do |f| 
  	f.html {render :index}
  	f.json {render :json => @city}
 	  end

  end

  def show
  	@city = City.friendly.find(params[:id])
  	
  	respond_to do |f| 
  	f.html {render :show}
  	f.json {render :json => @city}
 	  end
  end

  def tag_cloud
    @tags = Post.tag_counts_on(:tags)
  end
  	
end

app/helpers/cities_helper.rb
module CitiesHelper
	  include ActsAsTaggableOn::TagsHelper
end

app/views/cities/index.html.erb
<!-- mapbox -->

<div id="map-container">
	<iframe width='100%' height='100%px' frameBorder='0' src='https://a.tiles.mapbox.com/v4/paulkim517.n5f5cal1/attribution,zoompan,zoomwheel,geocoder,share.html?access_token=pk.eyJ1IjoicGF1bGtpbTUxNyIsImEiOiI4M2IxYzYxMTA0NTIzMjY1ZGEyYjcwNDdmMDgwYTdlOSJ9.l-q5F20plU7l2ArTn7HFXw'></iframe>
</div>

app/views/cities/show.html.erb
	<div id="jumbotron" class="jumbotron" style="background-image: linear-gradient(to bottom, rgba(0, 0, 0, 0.5) 0%, rgba(0, 0, 0, 0.5) 100%), url(<%= asset_path @city.image %>);">

		<div class="container">
			<h1 id="city-name"><%= @city.name %></h1>
		</div>

	</div>

	<div class="container">
		<div class="row">
			<div class="col-md-8 col-md-offset-2">
				<br><br>
				<%= link_to "New Post", new_city_post_path(@city, @post), class: "btn btn-success" %>
				<br><br>

				<% if @city.posts.any? %>

					<% @city.posts.reverse_each do |post| %>
						<div class="panel panel-warning">
							<div class="panel-heading">
								<%= image_tag post.user.avatar.url(:thumb), class: "thumbnail" %>
								<h3 class="panel-title username"> &nbsp<%= post.user.username %></h3>
							</div>
							<div class="panel-body">
								<p>Title: <%= post.title %> <br>Body: <%= post.body %> <br>
							  <% tag_cloud post.tag_counts, %w{s m l} do |tag, css_class| %>
    							<%= link_to tag.name, tag_path(tag.id), class: css_class %>
  							<% end %></p>
							</div>
							<% if post.user.id == session[:user_id] %>
								<div class="panel-footer">
									<%= link_to "Edit Post", edit_post_path(post), class: "btn btn-primary" %>
									<%= link_to "Delete Post",  post, method: :delete, class: "btn btn-danger"  %>
								</div>
							<% end %>
						</div>	
					<% end %>
				<% else %>
					<p>Please add a post<p>
				</div>
			</div>
		</div>
<% end %>